#!/usr/bin/env python 

import pandas as pd
from modules.scripts.metasheet_setup import updateMeta
from modules.utils import getTargetInfo 

#---------  CONFIG set up  ---------------
configfile: "config.yaml"  
config = updateMeta(config)
#-----------------------------------------

samples = pd.read_table("samplesheet.tsv").set_index("sample_name", drop=False)
SAMPLES = samples.index.values

rule all:
  input: getTargetInfo(config)

include: "modules/common.smk"
include: "modules/align.smk"

